"""Initial migration.

Revision ID: 367c4f150f69
Revises: 
Create Date: 2020-04-11 15:38:38.830576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367c4f150f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('attitude_score', sa.Integer(), nullable=True),
    sa.Column('cleanliness_score', sa.Integer(), nullable=True),
    sa.Column('taste_score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###
